free-delivery-offer() ::= <<
<!DOCTYPE html>
<html>
<head>
</head>
<body style="background-color: #f6f6f6;">

<div style="background-color: #ffffff; max-width: 600px; margin: 0 auto; overflow: hidden; border-radius: 5px; font-family: sans-serif;">
    <div style="background-color: #f6f6f6; padding-bottom: 10px; padding-top: 10px;">
        <img src="https://noodle-monster.co.uk/images/logo_grey.png" style="max-height: 40px;">
    </div>
    <div style="margin: 20px; font-size: 15px; font-weight: 300; color: #002E36; line-height: 1.5;">
        <div style="text-align: center; margin: 20px;">
            <img src="https://noodle-monster.co.uk/images/the-munchies.png" width="200" height="163">
        </div>
				<div style="text-align: center;">年中盛宴，Noodle Monster促銷活動火熱進行中！</div>
        <div style="text-align: center; margin-top: 0.5em;">訂單滿£19.99全英包郵 | 优惠6月29日結束</div>
        <div style="text-align: center; margin-top: 1.0em; font-weight: bold; font-size: 20px; color: #cb5a20; letter-spacing: 5px;">活動最後三天!</div>
				<br>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/taste-of-singapore.png">
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/category/noodles-singapore" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">新加坡泡面</a>
        </div>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/taste-of-taiwan.png">
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/category/mixed-source-taiwan-noodles" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">台湾拌面</a>
        </div>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/taste-of-japan.png">
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/category/noodles-japan" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">日本拉面</a>
        </div>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/taste-of-malaysia.png">
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/category/malaysia-instant-noodles" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">马来西亚泡面</a>
        </div>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/sun-dried-noodles.png">
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/brands/huijifood" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">有你一面</a>
        </div>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/free-delivery-for-orders-over-1999-1.png">
    </div>
    <div style="padding-top: 30px; padding-bottom: 15px; background-color: #f6f6f6; text-align: center; color: grey; font-size: 12px; letter-spacing: 0.8px;">
        @ 2021 Noodle-Monster. INC.
    </div>
</div>

</body>
</html>
>>