google-review-request(customerName) ::= <<
<!DOCTYPE html>
<html>
<head>
</head>
<body style="background-color: #f6f6f6;">

<div class="container" style="background-color: #ffffff; max-width: 600px; margin: 0 auto; overflow: hidden; border-radius: 5px; font-family: sans-serif;">
    <div class="header" style="background-color: #f6f6f6; padding-bottom: 10px; padding-top: 10px;">
        <img src="https://s3-eu-west-1.amazonaws.com/cawaii.co.uk/images/logo_grey.png" style="max-height: 40px;">
    </div>
    <div class="message" style="margin: 20px; font-size: 15px; font-weight: 300; color: #002E36; line-height: 1.5;">
        <div style="text-align: center; margin: 20px;">
            <img src="https://s3-eu-west-1.amazonaws.com/noodle-monster.co.uk/images/the-munchies.png" width="200"
                 height="163">
        </div>

        <h2 style="text-align: center; margin: 20px;">Hi $customerName$</h2>
        <div style="text-align: center;">Thank you for your recent purchase with <a href="https://noodle-monster.co.uk" target="_blank">Noodle Monster</a>! We really appreciate your business and hope you were happy with your order.</div>
        <br/>
        <div style="text-align: center;">We'd love to hear your feedback on how you feel about our service! If you could take a few minutes to leave us a review on <a href="https://g.page/NoodleMonsterUk/review?gm" target="_blank">Google</a>, we'd be so happy.</div>
        <br/>
        <div style="text-align: center;">To submit your review, simply click below and let us know what you think!</div>
        <div class="button" style="text-align: center; margin: 20px;">
            <a href="https://g.page/NoodleMonsterUk/review?gm" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">Write a Review</a>
        </div>
        <div style="text-align: center; font-weight: 600;">Thank you!</div>
        <br/>
        <p style="color: grey;">Kind regards,<br>Noodle-Monster Customer Service</p>
    </div>
    <div class="footer" style="padding-top: 30px; padding-bottom: 15px; background-color: #f6f6f6; text-align: center; color: grey; font-size: 12px; letter-spacing: 0.8px;">
        @ 2021 Noodle-Monster. INC.
    </div>
</div>

</body>
</html>
>>