new-product-20210615() ::= <<
<!DOCTYPE html>
<html>
<head>
</head>
<body style="background-color: #f6f6f6;">

<div style="background-color: #ffffff; max-width: 600px; margin: 0 auto; overflow: hidden; border-radius: 5px; font-family: sans-serif;">
    <div style="background-color: #f6f6f6; padding-bottom: 10px; padding-top: 10px;">
        <img src="https://noodle-monster.co.uk/images/logo_grey.png" style="max-height: 40px;">
    </div>
    <div style="margin: 20px; font-size: 15px; font-weight: 300; color: #002E36; line-height: 1.5;">
        <div style="text-align: center; margin: 20px;">
            <img src="https://noodle-monster.co.uk/images/the-munchies.png" width="200" height="163">
        </div>
        <div style="text-align: center;">【仲夏来袭】椅席炙手，空調沒有</div>
        <div style="text-align: center; margin-top: 0.5em;">【不想下廚】各式Noodle，談笑封侯</div>
        <div style="text-align: center; margin-top: 0.5em;">我們搜羅了許多你們投票選出的在英國最想吃的Noodle。來自天南地北，希望有你喜歡的。</div>
        <br/>
        <div style="margin-bottom: 0.5em;">
            <table style="width:100%; font-size: 14px;">
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/singapore-prima-taste-laksa-la-mian-185g-1.jpeg">
                	<div style="text-align: center;">百勝廚 叻沙拉麵</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/singapore-prima-taste-chili-crab-la-mian-160g-1.jpeg">
                	<div style="text-align: center;">百勝廚 辣椒螃蟹拉麵</div>
                </td>
              </tr>
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/singapore-prima-taste-curry-la-mian-178g-1.jpeg">
                	<div style="text-align: center;">百勝廚 咖哩拉麵</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/singapore-prima-taste-wholegrain-curry-la-mian-178g-1.jpeg">
                	<div style="text-align: center;">百勝廚 咖喱全麥拉麵</div>
                </td>
              </tr>
            </table>
        </div>
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/brands/primataste" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">查看 新加坡-百勝廚</a>
        </div>
        <br/>
        <div style="margin-bottom: 0.5em;">
            <table style="width:100%; font-size: 14px;">
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/malaysia-ibumie-penang-white-currymee-curry-1.jpeg">
                	<div style="text-align: center;">馬來西亞 檳城白咖哩面 105g x 4包</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/malaysia-ibumie-mi-goreng-asli-1.jpeg">
                	<div style="text-align: center;">馬來西亞 幹撈麵原味 80g x 5包</div>
                </td>
              </tr>
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/malaysia-ibumie-penang-ladmee-hot-pepper-1.jpeg">
                	<div style="text-align: center;">馬來西亞 檳城胡椒辣麵 75g x 5包</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/malaysia-ibumie-penang-harmee-prawn-1.jpeg">
                	<div style="text-align: center;">馬來西亞 檳城虾面 85g x 5包</div>
                </td>
              </tr>
            </table>
        </div>
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/brands/ibumie" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">查看 馬來西亞-IBUMIE</a>
        </div>
        <br/>
        <div style="margin-bottom: 0.5em;">
            <table style="width:100%; font-size: 14px;">
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/youniyimian-sun-dried-noodles-with-sichuan-pepper-1.jpeg">
                	<div style="text-align: center;">手工日晒面 爽口椒麻拌面 130g x 4包</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/youniyimian-sun-dried-dandan-flavor-noodles-1.jpeg">
                	<div style="text-align: center;">手工日晒面 担担拌面 118g x 4包</div>
                </td>
              </tr>
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/youniyimian-sun-dried-noodles-with-scallion-and-sischuan-pepper-1.jpeg">
                	<div style="text-align: center;">手工日晒面 葱油麻椒拌面 118g x 4包</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/youniyimian-sun-dried-noodles-with-capsicol-1.jpeg">
                	<div style="text-align: center;">手工日晒面 红油拌面 140g x 4包</div>
				</td>
              </tr>
            </table>
        </div>
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/brands/huijifood" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">查看 徽记食品-有你一面</a>
        </div>
        <br/>
        <div style="margin-bottom: 0.5em;">
            <table style="width:100%; font-size: 14px;">
              <tr style="margin-bottom: 0.5em;">
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/hakubaku-organic-cha-soba-270g-1.jpeg">
                	<div style="text-align: center;">HAKUBAKU 有机绿茶荞麦面 200g</div>
                </td>
                <td width="50%">
                	<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/products/hakubaku-organic-udon-270g-1.jpeg">
                	<div style="text-align: center;">HAKUBAKU 有机乌冬面 270g</div>
                </td>
              </tr>
            </table>
        </div>
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk/brands/hakubaku" target="_blank"
               style="font-size: 15px; text-decoration: none; display: inline-block; background: #f0c14b; color: #002E36; padding: 10px 20px 10px; border-radius: 5px; text-align: center;">查看 HAKUBAKU-有機面</a>
        </div>
    </div>
    <div style="padding-top: 30px; padding-bottom: 15px; background-color: #f6f6f6; text-align: center; color: grey; font-size: 12px; letter-spacing: 0.8px;">
        @ 2021 Noodle-Monster. INC.
    </div>
</div>

</body>
</html>
>>