now-support-google-pay-apple-pay() ::= <<
<!DOCTYPE html>
<html>
<head>
</head>
<body style="background-color: #f6f6f6;">

<div style="background-color: #ffffff; max-width: 600px; margin: 0 auto; overflow: hidden; border-radius: 5px; font-family: sans-serif;">
    <div style="background-color: #f6f6f6; padding-bottom: 10px; padding-top: 10px;">
        <img src="https://noodle-monster.co.uk/images/logo_grey.png" style="max-height: 40px;">
    </div>
    <div style="margin: 20px; font-size: 15px; font-weight: 300; color: #002E36; line-height: 1.5;">
        <div style="text-align: center; margin: 20px;">
            <a href="https://noodle-monster.co.uk"><img src="https://noodle-monster.co.uk/images/the-munchies.png" width="200" height="163"></a>
        </div>
				<div style="text-align: center;">Apply Pay和Google Pay，免去了您手动输入信用卡的麻烦，</div>
				<div style="text-align: center;">提供了一种更快、更便捷的付款方式！</div>
				<br>
				<a href="https://noodle-monster.co.uk"><img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/google-pay-apple-pay.jpg"></a>
        <p class="color-valencia"><b>使用方法:</b></p>
        <ol class="color-grey">
             <li>进入Payment页面后点击“Google Pay / Apple Pay"选项。</li>
             <li>根据您的设备和浏览器组合，您会看到"Apply Pay", "Google Pay"或者"Pay Now"按钮。（如下图）</li>
             <li>如果您的设备和浏览器不支持上述支付方式，请继续使用银行卡支付。</li>
        </ol>
				<img style="display: block; padding: 4px; background-color: #fff; vertical-align: middle; max-width: 100%; height: auto;" src="https://noodle-monster.co.uk/images/blog/payment-page.png">
    </div>
    <div style="padding-top: 30px; padding-bottom: 15px; background-color: #f6f6f6; text-align: center; color: grey; font-size: 12px; letter-spacing: 0.8px;">
        @ 2021 Noodle-Monster. INC.
    </div>
</div>

</body>
</html>
>>